name: wallpaper
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  provider: ^6.0.3
  hive: ^2.2.3
  fluttertoast: ^8.0.9
  logger: ^1.1.0
  file_encrypter: ^1.0.1
  flutter_archive: ^5.0.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  image_picker: ^0.8.6
  json_annotation: ^4.7.0
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_analytics: ^9.3.8
  internet_connection_checker: ^1.0.0+1
  quick_actions: ^1.0.0
  flutter_svg: ^1.1.5
  animations: ^2.0.7
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.6
  purchases_flutter: ^4.3.0
  flutter_displaymode: ^0.4.0
  flare_flutter: ^3.0.2
  carousel_slider: ^4.1.1
  permission_handler: ^10.1.0
  device_info_plus: ^6.0.0
  gallery_saver: ^2.3.2
  image: ^3.2.0
  image_editor: ^1.1.0
  google_sign_in: ^5.4.2
  flutter_share: ^2.0.0
  photofilters: ^3.0.1
  flutter_staggered_grid_view: ^0.4.0
  timeago: ^3.3.0
  photo_view: ^0.14.0
  palette_generator: ^0.3.3+2
  sliding_up_panel: ^2.0.0+1
  screenshot: ^1.2.3
  github: ^9.4.0
  flutter_mailer: ^2.0.1
  flutter_cache_manager: ^3.3.0
  device_apps: ^2.2.0
  get_it: ^7.2.0
  flutter_image_compress: ^1.1.3
  extended_image: ^6.3.1
  firebase_dynamic_links: ^4.3.11
  google_mobile_ads: ^2.0.1
  external_path: ^1.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: ^2.3.0
  hive_generator: ^1.1.3
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 500
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova Bold.otf
          weight: 600
        - asset: assets/fonts/Proxima Nova Extrabold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 800
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 900

    - family: JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
